Update app.js
Resolved: "/home/circleci/team12aero/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^

TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (/home/circleci/team12aero/node_modules/express/lib/router/index.js:458:13)
    at Function.<anonymous> (/home/circleci/team12aero/node_modules/express/lib/application.js:220:21)
    at Array.forEach (<anonymous>)
    at Function.use (/home/circleci/team12aero/node_modules/express/lib/application.js:217:7)
    at Object.<anonymous> (/home/circleci/team12aero/app.js:40:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3"